web/router.ex
defmodule Exshaker.Router do
  use Exshaker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Exshaker do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/games", GameController, only: [:index, :show] do
      resources "/races", RaceController, only: [:show]
    end
  end

  scope "/api", Exshaker do
    pipe_through :api

    get "/nicks/:id", NickController, :show
    post "/nicks", NickController, :create
  end
end

web/models/game.ex
defmodule Exshaker.Game do
  use Exshaker.Web, :model

  schema "games" do
    field :name, :string
    field :content, :string
    field :slug, :string
    field :description, :string
    has_many :races, Exshaker.Race
    has_many :syllables, Exshaker.Syllable
    has_many :nicks, Exshaker.Nick

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :content, :slug, :description])
    |> validate_required([:name, :content, :slug, :description])
  end
end

web/controllers/game_controller.ex
defmodule Exshaker.GameController do
  use Exshaker.Web, :controller

  alias Exshaker.Game
  alias Exshaker.Race

  def index(conn, _params) do
    games = Repo.all(Game)
    render(conn, "index.html", games: games)
  end

  def show(conn, %{"id" => id}) do
    game = Repo.get!(Game, id)
    races = Repo.all(from r in Race, where: r.game_id == ^game.id)

    render(conn, "show.html", game: game, races: races)
  end
end

web/views/game_view.ex
defmodule Exshaker.GameView do
  use Exshaker.Web, :view
end

web/templates/game/index.html.eex
<h2>Listing games</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Slug</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for game <- @games do %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.content %></td>
      <td><%= game.slug %></td>
      <td><%= game.description %></td>

      <td class="text-right">
        <%= link "Show", to: game_path(@conn, :show, game), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/game/show.html.eex
<h2>Show game</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @game.name %>
  </li>

  <li>
    <strong>Content:</strong>
    <%= @game.content %>
  </li>

  <li>
    <strong>Slug:</strong>
    <%= @game.slug %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @game.description %>
  </li>

</ul>

<h2>Listing races</h2>

<table class="table">
  <tbody>
<%= for race <- @races do %>
    <tr>
      <td><%= link race.name, to: game_race_path(@conn, :show, @game.id, race), class: "btn btn-default btn-xs" %></td>
    </tr>
<% end %>
  </tbody>
</table>